# Generated by Django 5.1.1 on 2024-10-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='themes',
            table=None,
        ),
    ]
