# Generated by Django 5.1.1 on 2024-10-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_themes_is_checked_alter_themes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
