# Generated by Django 5.1.1 on 2024-10-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_continuationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuationmodel',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.themes'),
            preserve_default=False,
        ),
    ]
