# Generated by Django 5.1.1 on 2024-10-12 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_continuationmodel_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 12, 13, 22, 41, 777019, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='themes',
            table='themes',
        ),
    ]
