# Generated by Django 5.1.1 on 2024-10-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_themes_created_at_alter_themes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
